#ifndef GEN_INT_H
#define GEN_INT_H

#include <ast_nodes.h>

generation_function_t generate_int_assignment;
generation_function_t generate_int_addition;
generation_function_t generate_int_multiplication;
generation_function_t generate_int_division;
generation_function_t generate_int_substraction;
generation_function_t generate_int_unary_plus;
generation_function_t generate_int_not_equal;
generation_function_t generate_int_equal;
generation_function_t generate_int_greater_than;
generation_function_t generate_int_greater_than_equal;

#endif
