#ifndef __OPCODES_H__
#define __OPCODES_H__

typedef enum opcode
{
    OPCODE_MOV,
    OPCODE_ADD,
    OPCODE_SUB,
    OPCODE_MUL,
    OPCODE_IMUL,
    OPCODE_DIV,
    OPCODE_XOR,
    OPCODE_AND,
    OPCODE_OR,
    OPCODE_JMP,
    OPCODE_PUSH,
    OPCODE_POP,
    OPCODE_JZ,
    OPCODE_JNZ,
    OPCODE_NOP,
    OPCODE_NEG,
    OPCODE_SETA,
    OPCODE_SETAE,
    OPCODE_SETB,
    OPCODE_SETBE,
    OPCODE_SETC,
    OPCODE_SETE,
    OPCODE_SETNE,
    OPCODE_SETG,
    OPCODE_SETGE,
    OPCODE_SETL,
    OPCODE_SETLE
} opcode_e;

typedef enum
{
	REGISTER_EAX,
	REGISTER_EBX,
	REGISTER_ECX,
	REGISTER_EDX,
	REGISTER_EDI,
	REGISTER_ESI
} register_e;

#endif
